### ISSUE TITLE
In Snowflake dialect `field/100` tokenizes as `Word(field/100)` instead of `Word(field),Div,Number(100)`

### ISSUE THREAD

**Issue by lustefaniak** [sqlparser-rs/sqlparser-rs#1008]
Changes in https://github.com/sqlparser-rs/sqlparser-rs/pull/841 broke division support when there are no whitespace characters around(before) `/` for Snowflake.

Right now, I don't know how to fix it properly, and I just disabled those chars from the Snowflake dialect in my fork.

**Comment by alamb** [comment]
Thank you @lustefaniak -- I will check out the proposed PR shortly
