### ISSUE TITLE
SQL validation doesnt work

### ISSUE THREAD

**Issue by kasvith** [sqlparser-rs/sqlparser-rs#1039]
**Behavior**
Lets use a `PostgreSQL` dialect and try to parse this query. it contains a MSSQL style syntax which is invalid on PostgreSQL

```sql
select top 10 * from orders
```

But instead of throwing an error, this query get perfectly parsed by the library.

I tested on

`PostgreSQL`, `MySQL` dialects. both parsed this invalid syntax

**Expected output:**
Should throw an error when invalid token is found

**Comment by tobyhede** [comment]
I think this is by design - the parser deliberately avoids semantic analysis. 

[The parser doesn't do much validation](https://github.com/sqlparser-rs/sqlparser-rs#syntax-vs-semantics)

**Comment by kasvith** [comment]
oh thanks @tobyhede
