### ISSUE TITLE
【bug】The error location is imprecise.

### ISSUE THREAD

**Issue by baoyachi** [sqlparser-rs/sqlparser-rs#1071]
The error location is imprecise. The current error AND2 is on the line 3, but the error report incorrectly indicates the line 1.

## the code 
```diff
#[test]
fn test_hello() {
    let sql = "SELECT a, b, 123, myfunc(b) \
           FROM table_1 \
-           WHERE a > b AND2 b < 100 \
           ORDER BY a DESC, b";

    let dialect = GenericDialect {}; // or AnsiDialect, or your own dialect ...

    let ast = Parser::parse_sql(&dialect, sql).unwrap();
}
```

## detail error
```bash
called `Result::unwrap()` on an `Err` value: ParserError("Expected end of statement, found: AND2 at Line: 1, Column 54")
thread 'test_hello' panicked at src/lib.rs:30:48:
called `Result::unwrap()` on an `Err` value: ParserError("Expected end of statement, found: AND2 at Line: 1, Column 54")
stack backtrace:
...
```

**Comment by alamb** [comment]
It definitely sounds like a bug -- thank you for the report @baoyachi

**Comment by Nikita-str** [comment]
There no bug, you use [newline skipping](https://doc.rust-lang.org/reference/tokens.html#:~:text=Line%2Dbreaks%20are,characters%20are%20ignored.):
>When an unescaped U+005C character (\) occurs immediately before a line break, then the line break character(s), and all immediately following (U+0020), \t (U+0009), \n (U+000A) and \r (U+0000D) characters are ignored.

So, `Rust` itself just remove spaces and `\n` in case of such strings:
```rust
#[test]
fn test_newline_skipping() {
    let sql = "SELECT a, b, 123, myfunc(b) \
           FROM table_1 \
           WHERE a > b AND2 b < 100 \
           ORDER BY a DESC, b";

    let sql_wo_newline_skipping = "SELECT a, b, 123, myfunc(b) FROM table_1 WHERE a > b AND2 b < 100 ORDER BY a DESC, b";
    
    assert_eq!(sql, sql_wo_newline_skipping);
}
```

If we pass string with newlines than all will be right:
```rust
#[test]
fn test_err_pos_correctness() {
    let sql = "SELECT a, b, 123, myfunc(b) 
           FROM table_1 
           WHERE a > b AND2 b < 100 
           ORDER BY a DESC, b";

    let dialect = GenericDialect {};
    
    let is_err_on_line_3 = Parser::parse_sql(&dialect, sql)
        .expect_err("expected error")
        .to_string()
        .contains("at Line: 3");

    assert!(is_err_on_line_3);
}
```

So, there no bug, issue can be closed.

**Comment by baoyachi** [comment]
@alamb 
The error text used in sqlparse rs is formatted instead of the original data, which changes the direct display of errors in SQL. This optimization can be referred to in Toml, which can achieve true row and column positioning.

See detail:https://github.com/toml-rs/toml/blob/ceec5d678a03b90e4eca77254c7ee6064b324ca2/crates/toml_edit/tests/testsuite/invalid.rs#L47-L70

**Comment by alamb** [comment]
Thank you for the analysis @Nikita-str   -- @baoyachi  do you have a suggested fix for this issue?
