### ISSUE TITLE
Parsing fails for postgres queries with `array_agg(tablenm.*)`

### ISSUE THREAD

**Issue by ReppCodes** [sqlparser-rs/sqlparser-rs#1088]
Hi!  I'm seeing some odd behavior on aggregate functions, and wanted to report it.

Minimal repro:
```rs
let _ = r#"create table if not exists sections_tbl(i int, j int, k int);"#;
let _ = r#"insert into sections_tbl VALUES (1,1,1);"#;

// this works fine in, e.g. psql for Postgres 16
let query = r#"select array_agg(sections_tbl.*) as sections from sections_tbl;"#;

// but throws an error in sqlparser
match Parser::parse_sql(&PostgreSqlDialect {}, query) {
    Ok(res) => println!("sqlparser works: {:?}", res),
    Err(e) => println!("sqlparser does not work: {}", e),
}

// this prints:
sqlparser does not work: sql parser error: Expected an identifier or a '*' after '.', found: * at Line: 1, Column 31
```

I tested this on two versions, including the latest:
```toml
sqlparser = "0.41.0"
# sqlparser = "0.36.1"
```

Of particular interest, this does not seem to be a more general issue of failing with `func(tablenm.*)`.
```rs
// AJR -- this one works in both psql and sqlparser
let query = r#"select greatest(sections_tbl.*) as sections from sections_tbl;"#;

match Parser::parse_sql(&PostgreSqlDialect {}, query) {
    Ok(res) => println!("sqlparser works: {:?}", res),
    Err(e) => println!("sqlparser does not work: {}", e),
}
```

**Comment by ReppCodes** [comment]
It looks like this was broken by `823635d2fcd2642254b14b5737c9758d96a9580b`, as the `Token::Mul` match arm is where we're failing out.  I think putting together a patch to re-add wildcard support in parse_prefix would solve this.  The special-casing for `parse_array_agg_expr` paths straight through `parse_subexpr` into `parse_prefix` and dies when it hits that missing match arm.

Is there any objection to me writing that up?  It probably means pulling the members of `WildcardExpr` enum back into the main `Expr` enum.

**Comment by alamb** [comment]
> Is there any objection to me writing that up? It probably means pulling the members of `WildcardExpr` enum back into the main `Expr` enum.

I have no objection given the description you provide. I would be happy to review a PR

**Comment by ReppCodes** [comment]
Sounds good, I've opened https://github.com/sqlparser-rs/sqlparser-rs/pull/1093 to address this, and added some light test coverage to help prevent future regressions.

**Comment by ReppCodes** [comment]
https://github.com/sqlparser-rs/sqlparser-rs/pull/1093 is merged, this bug is now fixed.
