### ISSUE TITLE
GROUP BY () not supported

### ISSUE THREAD

**Issue by michael-2956** [sqlparser-rs/sqlparser-rs#1092]
Hello. First of all, thanks for this amazing project!
I've ran into an issue that explicit `GROUP BY ()` is not supported.

For example, when we write:
`SELECT SUM (value) from sales`,
it is supposed to be the same as:
`SELECT SUM (value) from sales group by ()`,
but the latter is not parseable by the parser. It produces:
`ParserError("Expected an expression:, found: )")`.

I suppose that the issue is that it expects a row expression there, but () is just a special syntax for grouping by nothing.
You technically can specify `GROUP BY (), value`, which would just group by `value`, but if only () is present it treats all rows like a single group.

How would you suggest fixing this?

**Comment by alamb** [comment]
I would recommend finding a sql reference for the syntax (aka which database invented / used this syntax) to understand what `()` means in this context and then update the parser accordingly

**Comment by michael-2956** [comment]
() can be used in GROUPING SETS, ROLLUP, etc. It is used to include "single group" into the list of sets, for example:
```sql
SELECT count(*), o_orderkey, o_custkey
FROM orders
GROUP BY GROUPING SETS ((), (o_orderkey, o_custkey));
```
Will return something like:
```
 count | o_orderkey | o_custkey 
-------+------------+-----------
     4 |            |          
     1 |          1 |         1
     1 |          4 |         4
     1 |          3 |         3
     1 |          2 |         2
```
More useful here than in the example I provided in issue description actually :)

**Comment by alamb** [comment]
Thanks for the update @michael-2956  -- since this is an actual feature gap I'll plan to leave this issue open in case anyone else runs into the limitation and might benefit from your research.

**Comment by git-hulk** [comment]
Hi @alamb, I would like to take this task, and I want to hear your thoughts before starting the implementation.

We can implement this feature in three ways:

1. Add a dedicated group by type like GroupByExpr::All, maybe call it `GroupByExpr::Nothing`
2. Regard `()` as a special case for `GroupByExpr::Expressions` and an value like Value::Nothing, then return `GroupByExpr::Expressions(vec![Value::Nothing])` to represent the group by nothing clause

I think the better solution is to use `GroupByExpr::Expressions(vec![])` to represent the `group by nothing` condition, but it's now used to represent the `GROUP BY` clause doesn't exist and we should not break this pattern. So I prefer using solution 1 which adds a new enum value GroupByExpr::Nothing for this purpose. What do you think?

**Comment by iffyio** [comment]
Sounds good! Representing it as an new variant sounds reasonable to me! (i.e. option 1. with `GroupBy::Nothing`)

**Comment by git-hulk** [comment]
@iffyio Thank you!
