### ISSUE TITLE
support more dialects of `struct` creation

### ISSUE THREAD

**Issue by universalmind303** [sqlparser-rs/sqlparser-rs#1129]
Currently the only struct syntax that is support is bigquery's dialect. 

It'd be nice to support duckdb's struct literal syntax https://duckdb.org/docs/sql/data_types/struct. 

see also
https://github.com/GlareDB/glaredb/issues/2112

**Comment by alamb** [comment]
BTW see https://github.com/sqlparser-rs/sqlparser-rs/pull/1194 where this is beginning
