### ISSUE TITLE
snowflake describe table not supported

### ISSUE THREAD

**Issue by vieux** [sqlparser-rs/sqlparser-rs#1160]
Snowflake actually uses the keyword TABLE after DESC[RIBE] and it doesn't seems to be supported at the moment

See https://docs.snowflake.com/en/sql-reference/sql/desc-table

**Comment by alamb** [comment]
Possibly related: https://github.com/sqlparser-rs/sqlparser-rs/pull/1156

**Comment by vieux** [comment]
I did see this PR before opening this issue and I don't believe they are related, after quickly looking at the code, I don't think the current parser supports `DESCRIBE TABLE <table>`, only `DESCRIBE <table>`
