### ISSUE TITLE
Whether Sqlparser-rs can support SQL rewriting?

### ISSUE THREAD

**Issue by groobyming** [sqlparser-rs/sqlparser-rs#1165]
Our business scenario requires syntax checking and statement rewriting of the original SQL, such as replacing table names or where conditions. I would like to know if it can meet the needs of our scenario.

**Comment by alamb** [comment]
Yes, this is possible

There is the built in Visitor trait:
https://docs.rs/sqlparser/latest/sqlparser/ast/trait.Visitor.html

You can also explicitly match each ast node and manually do whatever rewrite you need

**Comment by groobyming** [comment]
@alamb Thanks for the reply. Also, is it possible to modify the original Ast syntax tree and restore the modified ast syntax tree to an sql text, eg:  SQL text => Ast => modified Ast => SQL text

**Comment by alamb** [comment]
> @alamb Thanks for the reply. Also, is it possible to modify the original Ast syntax tree and restore the modified ast syntax tree to an sql text, eg: SQL text => Ast => modified Ast => SQL text

Yes, you can use the Display impl of the AST nodes to get the sql back:

```rust
let sql_text = parsed_ast.to_string()
```

**Comment by groobyming** [comment]
@alamb Thank you, I will give it a try and see how it goes
