### ISSUE TITLE
SUBSTRING function calls are always formatted as ` SUBSTRING(... FROM ... FOR ...)`

### ISSUE THREAD

**Issue by lovasoa** [sqlparser-rs/sqlparser-rs#1168]
Parsing the following valid SQLite statement:

```sql
select substring('xxx', 1, 2)
```

then dumping the parsed result as sql results in the following syntax, which is invalid in SQLite:

```sql
select SUBSTRING('xxx' FROM 1 FOR 2)
```

**Comment by jmaness** [comment]
Perhaps https://github.com/sqlparser-rs/sqlparser-rs/issues/914 is related, and the easiest fix is probably to add this to `src/dialect/sqlite.rs`

```
    fn supports_substring_from_for_expr(&self) -> bool {
        false
    }
```

See https://github.com/sqlparser-rs/sqlparser-rs/pull/947/files#diff-6f6a082c3ddfc1f16cc4a455e3e2e2d2508f77b682ab18cabee69471bbb3edb3R37 for how this was implemented for `mssql.rs`

**Comment by lovasoa** [comment]
Hmm, I'd prefer always allowing parsing of both, and have the exact syntax variant stored in the parsed syntax tree.

Changing the dialect won't help with correct serialization.

**Comment by alamb** [comment]
>  and have the exact syntax variant stored in the parsed syntax tree.

I agree this would be best. 

What it means in practice is to add some field / structure to the AST node that distinguishes between the two syntaxes

It seems like there is already a `special` flag:

https://docs.rs/sqlparser/latest/sqlparser/ast/enum.Expr.html#variant.Substring.field.special

Maybe that needs to be fixed 🤔

**Comment by alamb** [comment]
> What does the current "special" flag mean?

🤔  it appears to be for the case described in this issue:

https://github.com/sqlparser-rs/sqlparser-rs/blob/ef4668075b659be8d83c8e6795f310e32c3f6946/src/ast/mod.rs#L567-L569

**Comment by alamb** [comment]
(it would be nice if that comment was `///` so it appeared in the docstrings too

**Comment by jmaness** [comment]
@alamb I added `special` in that case based on our discussion at https://github.com/sqlparser-rs/sqlparser-rs/issues/914#issuecomment-1641943127. However, I'm certainly in favor of changing that.

**Comment by alamb** [comment]
> modify the Expr::Substring type and parser to store information describing the specific SUBSTRING variant?

I think this makes sense to me at a high level (store in the AST information about what specific SUBSTRING variant was in the orignal query so that it can be reconstructed).

Thanks @jmaness
