### ISSUE TITLE
Support Struct datatype parsing for GenericDialect

### ISSUE THREAD

**Issue by duongcongtoai** [sqlparser-rs/sqlparser-rs#1240]
Current BigQueryDialect is capable of parsing struct data type such as
```
create table t (s struct<n int, s varchar>);
```
According to [README](https://github.com/sqlparser-rs/sqlparser-rs/tree/0b5722afbfb60c3e3a354bc7c7dc02cb7803b807?tab=readme-ov-file#new-syntax), this feature should also support GenericDialect, however in current code, before parsing this syntax, we [only allow BigQueryDialect to have this syntax](https://github.com/sqlparser-rs/sqlparser-rs/blob/2f437db2a68724e4ae709df22f53999d24804ac7/src/parser/mod.rs#L5280)

**Comment by jayzhan211** [comment]
Can we also support syntax with '()', like `create table t (s struct(n int, s varchar));` like duckdb

**Comment by duongcongtoai** [comment]
https://github.com/sqlparser-rs/sqlparser-rs/blob/2f437db2a68724e4ae709df22f53999d24804ac7/src/parser/mod.rs#L1903
Then i think we can add | LParen here

**Comment by alamb** [comment]
@duongcongtoai  filed https://github.com/sqlparser-rs/sqlparser-rs/issues/1245 as a follow on. THank you
