### ISSUE TITLE
Need suggestions for supporting more table modifiers

### ISSUE THREAD

**Issue by git-hulk** [sqlparser-rs/sqlparser-rs#1329]
Currently, the parser is using [TableFactor](https://github.com/sqlparser-rs/sqlparser-rs/blob/44d7a20f641c9cd8f0c3e08f7d77f02534452ce8/src/ast/query.rs#L861) which is an enum to represent the table expression,
so we need to add the field to every enum value if would like to add a common modifier(like table name alias) for the table.

I'm not sure if it's good to add new fields for every enum value like the existing `alias`,
or should I add an extra layer to support more table modifiers like the following:

```Rust
pub enum TableFactor {
  table : Table {
    ....
    alias :Option<TableAlias>,
   
    +xxx: Option<yyy>,
  },
  Derived {
    lateral: bool,
    subquery: Box<Query>,
    alias: Option<TableAlias>,

    +xxx: Option<yyy>,
   },
   ...

}
```

or

```Rust
pub struct TableExpr {
  factor: TableFactor,
  alias: Option<TableAlias>,
  +xxx: Option<yyy>,
}
```

**Comment by git-hulk** [comment]
@alamb @iffyio What do you think about this? please let me know if I didn't express my point clearly, thank you!

**Comment by iffyio** [comment]
hmm yeah I think that would be reasonable change, to avoid having to add new fields to all variants. Deferring to @alamb for thoughts as well if you see any downsides with this?

**Comment by git-hulk** [comment]
@iffyio Thank you! I also prefer to the second solution. I might make a separate PR to resolve this before adding more fields to make the context clearer. And let’s wait for alamb’s thoughts.

**Comment by alamb** [comment]
> hmm yeah I think that would be reasonable change, to avoid having to add new fields to all variants. Deferring to @alamb for thoughts as well if you see any downsides with this?

The upside of following the existing pattern (add fields to all variants) is that
1. It follows the existing pattern and thus keeps the code more constent
2. It would likely reduce the changes needed downstream when the new API came out

Without a proposed PR I am not sure I have enough information to make a judgement between them

**Comment by git-hulk** [comment]
Thanks all for the reply. Yes, it might need to change many places to replace the old TableFactor. I might propose the change to see if that makes sense.

**Comment by git-hulk** [comment]
It needs to change many places including changing the pub visitor like `visit_table_factor`, I felt it's not a good idea to do this now. So I would like to close this issue and follow the existing pattern, and we can raise a new discussion if needed.

Thanks again for everyone's reply.
