### ISSUE TITLE
add support for `WITH ORDINALITY`

### ISSUE THREAD

**Issue by lovasoa** [sqlparser-rs/sqlparser-rs#1336]
The following is valid sql, and works in postgres, but cannot be parsed with sqlparser:

```sql
select * from my_srf() with ordinality;
```

https://www.postgresql.org/docs/current/functions-srf.html

Initially reported in https://github.com/lovasoa/SQLpage/discussions/491#discussioncomment-9986790

**Comment by git-hulk** [comment]
@lovasoa Are you working on this? I want to fix it if no one is on it.

**Comment by lovasoa** [comment]
I'm not working on it, go for it! Thanks!
