### ISSUE TITLE
`CEIL` and `FLOOR` do not support comma syntax

### ISSUE THREAD

**Issue by seve-martinez** [sqlparser-rs/sqlparser-rs#1376]
The current implementation only supports `CEIL`/`FLOOR` calls when including `TO <DateTimeField>`. However this syntax appears to be rare and so far I've only found it supported in [Kinesis](https://docs.aws.amazon.com/kinesisanalytics/latest/sqlref/sql-reference-ceil.html), which isn't supported by `sqlparser` at all.

The majority of dialects support a single expression, or an expression and a scale separated by a comma:
```sql
SELECT CEIL(321.56, 1)

-- prints 321.6

SELECT CEIL(321.56)
-- prints 322
```

[Snowflake](https://docs.snowflake.com/en/sql-reference/functions/ceil)
[BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/mathematical_functions#ceil)
[Hive](https://www.tutorialspoint.com/hive/hive_built_in_functions.htm#:~:text=2.0-,ceil()%20function,-hive%3E%20SELECT)
[ClickHouse](https://clickhouse.com/docs/en/sql-reference/functions/rounding-functions#ceiling)
[DuckDb](https://duckdb.org/docs/sql/functions/numeric.html#ceilx)
[MsSql](https://www.w3schools.com/sql/func_sqlserver_ceiling.asp)
[MySql](https://www.w3schools.com/sql/func_mysql_ceil.asp)
[Postgres](https://www.postgresqltutorial.com/postgresql-math-functions/postgresql-ceil/)
[Redshift](https://docs.aws.amazon.com/redshift/latest/dg/r_CEILING_FLOOR.html)
[SQLite](https://www.sqlite.org/lang_mathfunc.html#:~:text=arctangent%20of%20X.-,ceil(X)%0Aceiling(X),-Return%20the%20first)

The existing impl:
https://github.com/sqlparser-rs/sqlparser-rs/blob/1e209d87415a5adfedccac8cee3e2860122e4acb/src/parser/mod.rs#L1694-L1716

Because the `CEIL`/`FLOOR` [expressions](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/mod.rs#L652-L662) expect a `DateTimeField`, I'm not sure it makes sense to just pass a numeric literal to this and force into a `Custom(Ident)` type.

Happy to open a PR for this, but wanted to understand the best way to handle `field` attribute here.

**Comment by git-hulk** [comment]
I think a better way is to change the field to an enum like:

```Rust
{
   to_datetime: DateTimeField,
   precision: Number,
}
```

But this would also have a slight behavior change on `Floor/Ceil` expression.

@iffyio What do you think about this?

**Comment by iffyio** [comment]
Oh that's interesting, I think its a bit strange for the parser to support the `CEIL(x TO y)` syntax given none of the supported dialects do, looking at the [PR discussion](https://github.com/sqlparser-rs/sqlparser-rs/pull/635#issuecomment-1265711078) it seems it was intentional at the time at least (not sure if its still valid since then) so we could just as well preserve the current syntax.

Yeah I think representing the extra argument as an enum, merging it with the datetime sounds reasonable!
