### ISSUE TITLE
Regression: `describe table;` is now invalid, wasn't previously

### ISSUE THREAD

**Issue by samuelcolvin** [sqlparser-rs/sqlparser-rs#1385]
While working on https://github.com/apache/datafusion/pull/12014 I noticed that

```sql
describe table;
```

Is now invalid SQL, presumably `table` is now a keyword or similar now?

Error:

```
ParserError("Expected: identifier, found: ; at Line: 1, Column: 15"
```

Simple failing test:

```rs
#[test]
fn test_describe_table() {
    Parser::parse_sql(&GenericDialect {}, "describe table;").unwrap();
}
```

**Comment by alamb** [comment]
Thank you @samuelcolvin  -- I will fix this

**Comment by alamb** [comment]
(note this code has not been released yet so this does not affect 0.49.0 or earier and we plan to fix it prior to releasing 0.50.0)

**Comment by alamb** [comment]
I think this came in via #1351

**Comment by alamb** [comment]
Proposed fix: https://github.com/sqlparser-rs/sqlparser-rs/pull/1386
