### ISSUE TITLE
HiveDialect doesn't support create table with PARTITIONED BY and CLUSTERED BY clause

### ISSUE THREAD

**Issue by wugeer** [sqlparser-rs/sqlparser-rs#1395]
When I used the Hive dialect to parse the following Hive SQL, I encountered the following error.
```
    CREATE TABLE user_info_bucketed(user_id BIGINT, firstname STRING, lastname STRING)
    COMMENT 'A bucketed copy of user_info'
    PARTITIONED BY(ds STRING)
    CLUSTERED BY(user_id) INTO 256 BUCKETS;
```
with error
```
Err(ParserError("Expected: end of statement, found: PARTITIONED at Line: 4, Column: 5"))
```
Here is the code I tested.
```rust
use sqlparser::dialect::HiveDialect;
use sqlparser::parser::Parser;

fn main() {
    let query = r#"
    CREATE TABLE user_info_bucketed(user_id BIGINT, firstname STRING, lastname STRING)
    COMMENT 'A bucketed copy of user_info'
    PARTITIONED BY(ds STRING)
    CLUSTERED BY(user_id) INTO 256 BUCKETS;"#;
    let dialect = HiveDialect {};
    let ast = Parser::parse_sql(&dialect, query);
    println!("ast={:?}", ast);
}
```

![image](https://github.com/user-attachments/assets/7ec8cccd-dfad-4ef9-af4c-4f6cebd51b68)

**Comment by git-hulk** [comment]
@wugeer Yes, it hasn't supported parsing `COMMENT` after the table column definition yet, nor has the `CLUSTERED BY` clause. I can support both of them if you want this feature.

**Comment by git-hulk** [comment]
@wugeer  Yes, it hasn't supported parsing COMMENT after the table column definition yet, nor has the CLUSTERED BY clause. I can support both of them if you want this feature.

**Comment by wugeer** [comment]
> @wugeer Yes, it hasn't supported parsing COMMENT after the table column definition yet, nor has the CLUSTERED BY clause. I can support both of them if you want this feature.

@git-hulk That sounds awesome! Thank you for help! :)

**Comment by git-hulk** [comment]
@wugeer Your SQL should be valid after removing the table comment line. For parsing the hive comment, I need to add an extra field `hive_comment` since it follows after the column definitions and other dialects are not, and it cannot know the dialect information while generating SQL by AST. What do you think about this? @alamb @iffyio

**Comment by wugeer** [comment]
@git-hulk Thank you for your continued attention and contribution to this issue.

**Comment by iffyio** [comment]
@git-hulk we can probably have as part of the `CommentDef` enum? e.g. if we add a new variant like `CommentDef::AfterColumnDefsWithoutEq(String)` would provide the required info in the display impl of `CreateTable` to know where to place the comment.

**Comment by git-hulk** [comment]
> @git-hulk we can probably have as part of the `CommentDef` enum? e.g. if we add a new variant like `CommentDef::AfterColumnDefsWithoutEq(String)` would provide the required info in the display impl of `CreateTable` to know where to place the comment.

Good advice. I have to say whenever I need better advice, it's always right to call @iffyio. ❤️
