### ISSUE TITLE
Support RLS statements

### ISSUE THREAD

**Issue by wyozi** [sqlparser-rs/sqlparser-rs#1404]
Hey, I'm working on a project where I would like to parse and transform (among others) RLS policy migrations.

Namely, stuff like

```sql
create policy "authorize read access"
on "public"."accounting_entries"
as permissive
for select
to public
using (( SELECT authorize_company(accounting_entries.company_id) ));
```

and 

```
drop policy "Users can update own profile." on "public"."profiles";
```

Would it be possible to add support for these?

**Comment by git-hulk** [comment]
@wyozi It would be nice if you can provide the documentation link to which dialect supports this syntax.

**Comment by wyozi** [comment]
Ah of course, this is Postgres dialect. I'm so used to working in the Postgres world that I sometimes forget how different the dialects are 😅

**Comment by git-hulk** [comment]
@wyozi Thank you! I will support this when I get time.
