### ISSUE TITLE
The redundant punctuation in "expected()"

### ISSUE THREAD

**Issue by Fischer0522** [sqlparser-rs/sqlparser-rs#1433]
The `expected()` function will format the message in accordance with `format!("Expected: {expected}, found: {found}")`. However, when `expected()` is called by `parse_prefix()` at line 1254 in mod.rs, the parameter is "an expression:". Consequently, the formatted message is "Expected: an expression:, found: EOF". The ":," appears redundant.

Related code:
```Rust
    /// Report `found` was encountered instead of `expected`
    pub fn expected<T>(&self, expected: &str, found: TokenWithLocation) -> Result<T, ParserError> {
        parser_err!(
            format!("Expected: {expected}, found: {found}"),
            found.location
        )
    }

// in parse_prefix()
            _ => self.expected("an expression:", next_token),
```

**Comment by Fischer0522** [comment]
Perhaps “Expected: an expression, found: EOF” is a more appropriate format. Please review it @alamb

**Comment by git-hulk** [comment]
It would be good to remove the redundant `:`. Also, maybe you can check if other places which use `expect` have similar issues.

**Comment by Fischer0522** [comment]
> It should be good to remove the redundant `:`. Also, maybe you can check if other places which use `expect` have similar issues.
I have checked all places that use `expect`. This is the only place where this problem occurs. please check this pr #1434

**Comment by git-hulk** [comment]
@Fischer0522 This issue can be closed now.
