### ISSUE TITLE
Automate release process

### ISSUE THREAD

**Issue by Dandandan** [sqlparser-rs/sqlparser-rs#218]
Now that sqlparser-rs is under a new repo and shared with multiple owners/maintainers, it makes sense to standardize the release process a bit.

I was thinking of publishing a crate automatically after a release has been tagged. This way we can also use the GitHub release functionality to organize / document releases: https://help.github.com/en/github/administering-a-repository/managing-releases-in-a-repository

We can use the same implementation as is used in @maxcountryman project https://github.com/maxcountryman/forma/blob/main/.github/workflows/main.yml#L87

**Comment by Dandandan** [comment]
I am willing to take this up.
But I think I need access to the repo to add a secret.

If this sounds like a good idea, can anybody @andygrove @nickolay either add a token or add permissions for me to add this token `CRATES_TOKEN`?

**Comment by AugustoFKL** [comment]
@Dandandan @alamb I think this is still an "issue," right: If I recall correctly, the release is done manually by Mr. Lamb up to date.

What do you think about this? Can I take this up, or should I keep the release on Mr. Andrew's hand for now?

**Comment by Dandandan** [comment]
Releasing is mostly automated. See:
https://github.com/sqlparser-rs/sqlparser-rs/blob/main/docs/releasing.md

**Comment by AugustoFKL** [comment]
> Releasing is mostly automated. See: https://github.com/sqlparser-rs/sqlparser-rs/blob/main/docs/releasing.md

Thanks, @Dandandan!!

**Comment by alamb** [comment]
Yeah, the only thing that isn't automated is the creation of release notes

**Comment by AugustoFKL** [comment]
@alamb, maybe we can start using [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/) like [Angular](https://github.com/angular/angular/blob/22b96b9/CONTRIBUTING.md#-commit-message-guidelines)...?

**Comment by alamb** [comment]
We use https://github.com/github-changelog-generator/github-changelog-generator for arrow-rs and arrow-datafusion -- it works pretty well and may save some time -- though the biggest time sink is basically data cleansing -- ensuring the PR titles / descriptions make sense and are consistent

**Comment by AugustoFKL** [comment]
@alamb, I'll take a look and try it out!

If the pattern is conventional commits, I can start validating both PR titles and commits. Otherwise, I can learn the pattern and maybe, add a validation later on CI/CD; what do you think? Should be pretty doable with some complex regex

**Comment by alamb** [comment]
> If the pattern is conventional commits, 

I have personally found that simply enforcing the conventional commit style (as we do in https://github.com/influxdata/influxdb_iox) is not sufficient to ensure the content is meaningful. For example, most PRs to this repo are features so would have a `feat:` prefix in conventional commits. However, the content after the `feat:` is what has the valuable information. 

When I do PR reviews I focus more on ensuring that the title reflects the PRs content which I have not found a good way to automate yet

Thus I think the overhead (of getting contributors to use conventional commit messages) outweighs the benefits

If you want to enforce conventional commits in this repo, that would be fine me -- there are existing github actions that do this so I don't think you need to make your own regex unless you want. I can help find the right pre-existing action if you need help.
