### ISSUE TITLE
Anybody home? 

### ISSUE THREAD

**Issue by eyalleshem** [sqlparser-rs/sqlparser-rs#274]
Hi , 
Before 3 weeks i open 4 PR's , and still didn't got any comment on that . 
I guess it's related to the august vacations :)  ,  but as it's very different form my experience with previous PR's , I Just want to make sure that this repo still maintained and welcoming contribution.  

I will take advantage of the opportunity to also thank @nickolay for his  previous reviews  - that I learned a lot from them !  

thanks a lot , 
eyal 
@nickolay , @Dandandan , @maxcountryman

**Comment by nickolay** [comment]
Hey Eyal! I know it sucks to not get timely responses, and I'm sorry about that. It's nice to hear that you appreciate (and not loathe!) my reviews, but doing them takes time, which is unfortunately limited. I hope to get some help maintaining this project, as keeping up the pace is proving hard to pull off.

Also, trying to maintain a FIFO queue was probably a mistake on my part - being stuck on one of PRs, shouldn't result in me avoiding the others just to be fair...

**Comment by Dandandan** [comment]
Hey @eyalleshem having some weeks vacation at the moment. I hope to continue contributing again a bit more actively after that!

**Comment by eyalsatori** [comment]
Good to know :) !! 
Thanks @nickolay  and @Dandandan , If I could give some help i will be happy to take part .

**Comment by eyalleshem** [comment]
Good to know :) !!
Thanks @nickolay and @Dandandan , If I could give some help i will be happy to take part .

**Comment by alamb** [comment]
I am trying to keep the lights on with reviews now, but this crate is not likely to get major changes / large additional bandwidth anytime soon
