### ISSUE TITLE
Where should this repo live?

### ISSUE THREAD

**Issue by andygrove** [sqlparser-rs/sqlparser-rs#308]
Now that Ballista has been donated to Apache Arrow, it seems confusing to keep the `sqlparser-rs` project under the `ballista-compute` GitHub org and I am wondering where this project should live now.

Here are some options:

1. I could just move it back to `andygrove/sqlparser-rs`.
2. We could see if we could donate this project to Apache Arrow but this doesn't seem like a natural fit given that this is a general-purpose SQL parser.
3. Create a new GtiHub org for general-purpose database-related crates and add this as the first project?
4. Something else?

I would love to hear opinions on this. I am no longer actively involved in the project but want to make it easy for others to continue working on it.

**Comment by andygrove** [comment]
@nickolay @benesch @Dandandan @houqp @seddonm1 Let me know if you have any opinions on this

**Comment by Dandandan** [comment]
I am not sure what the best option to do here would be.
I would say

1. keep it under *something like* the current structure, which is some GitHub org and
2. shared with the current maintainers.

**Comment by houqp** [comment]
I would prefer github org over personal account so it provides more flexibility for access control, for example, creating different teams with different levels of permissions. If there are other projects that we can move into a general purpose rust db github org, then it's a better route, other wise keeping it in ballista in the short term doesn't seem too bad.

**Comment by andygrove** [comment]
The repo has moved to https://github.com/sqlparser-rs/sqlparser-rs for now. We can consider renaming this org to something more generic if we want to add other crates.
