### ISSUE TITLE
#[non_exhaustive] on most enum types

### ISSUE THREAD

**Issue by 0xA537FD** [sqlparser-rs/sqlparser-rs#350]
I would like to suggest to use the `#[non_exhaustive]` on most enum types as many of them will most likely be extended in the future and this would enforce the user of the library to use a catch all arm in any `match`.

If you agree we could discuss on which enums it would be reasonable or whether every enum should have it and I would do the changes.

**Comment by alamb** [comment]
According to  https://doc.rust-lang.org/reference/attributes/type_system.html

> Non-exhaustive types cannot be constructed outside of the defining crate:

This seems like it may be a fairly significant impediment to using `sqlparser-rs`

**Comment by Dandandan** [comment]
Counterargument: by adding a `#[non_exhaustive]`, each implementation is required to a catch all arm, which might require for the implementation to be fallible / return an `Err` or `Option` (which makes code more complex). Another downside is that with a next upgrade which introduces the new arm, the downstream library can not easily upgrade by implementing the extra arms by following/fixing the compilation errors.

**Comment by 0xA537FD** [comment]
yeah on second thought this seems like a rather bad idea :)
