### ISSUE TITLE
[Discussion] Add `gluesql` in README as an implemented open source library

### ISSUE THREAD

**Issue by MRGRAVITY817** [sqlparser-rs/sqlparser-rs#354]
![image](https://user-images.githubusercontent.com/41038636/133281571-c80f319a-5ca4-4f45-8045-d2d1fd478aaa.png)

GlueSQL is trending recently, and it uses `sqlparser-rs`.
https://github.com/gluesql/gluesql
https://github.com/trending/rust

**Comment by houqp** [comment]
Please feel free to send us a PR @MRGRAVITY817

**Comment by alamb** [comment]
Closed in https://github.com/sqlparser-rs/sqlparser-rs/pull/355
