### ISSUE TITLE
The current parser does not support parsing create database, No one calls parse_create_database function

### ISSUE THREAD

**Issue by SGZW** [sqlparser-rs/sqlparser-rs#359]

**Comment by SGZW** [comment]
can i take a pr to fix it ?

**Comment by houqp** [comment]
Yes, please feel free to send us a PR.

**Comment by alamb** [comment]
🙏  thank you @SGZW

**Comment by mikezhouhan** [comment]
still not fixed, how is it going bro

**Comment by AugustoFKL** [comment]
@alamb can this be closed? It is deprecated, as https://github.com/sqlparser-rs/sqlparser-rs/pull/451 resolves this.

**Comment by alamb** [comment]
Agreed -- thank you @AugustoFKL
