### ISSUE TITLE
Cannot distinguish between `SELECT * FROM foo` and `SELECT * FROM foo()`

### ISSUE THREAD

**Issue by not-my-profile** [sqlparser-rs/sqlparser-rs#405]
`sqlparser::ast::TableFactor::Table` just represents the arguments as a `Vec<FunctionArg>` both
`SELECT * FROM foo` and `SELECT * FROM foo()` and are parsed as:

```
Table { name: ObjectName([Ident { value: "foo", quote_style: None }]), alias: None, args: [], with_hints: [] }
```

This is apparently a regression that was introduced in 5652b4676c65f0875fd8c4849dd7cb27c819bef6 (#73).

**Comment by alamb** [comment]
@not-my-profile  we would be happy to accept a proposed fix
