### ISSUE TITLE
the syntax 'limit #,#' is not supported

### ISSUE THREAD

**Issue by Uchiha007** [sqlparser-rs/sqlparser-rs#406]

**Comment by not-my-profile** [comment]
From which SQL dialect is this?

**Comment by Uchiha007** [comment]
AnsiDialect, MySqlDialect

**Comment by alamb** [comment]
https://github.com/sqlparser-rs/sqlparser-rs/pull/370 attempts to add support for the syntax, but I am little concerned with the implementation. I'll try and whip up a new PR
