### ISSUE TITLE
Where is 'Statement'?

### ISSUE THREAD

**Issue by asad-awadia** [sqlparser-rs/sqlparser-rs#448]
I am using parser to get an ast which returns a vector of statements but i cant find what statement is and what methods are available on it

**Comment by poonai** [comment]
`Statement` is a `enum`. you can find it's definition here https://github.com/sqlparser-rs/sqlparser-rs/blob/main/src/ast/mod.rs#L687

**Comment by asad-awadia** [comment]
Thanks

**Comment by asad-awadia** [comment]
@poonai how to make statement implement serialize type to convert to json?
