### ISSUE TITLE
Add formatter to output AST back as SQL Statement

### ISSUE THREAD

**Issue by cphares** [sqlparser-rs/sqlparser-rs#460]
As a DBA, I would love the ability to take a statement, load it into an AST, do some manipulation on the AST, and then output the resultant SQL statement.

*Very* new to RUST so not sure how difficult this might be to accomplish but would be incredibly useful!

**Comment by poonai** [comment]
This can be achieved by just printing the statement.

I do the exact same at inspektor

here is the example https://github.com/poonai/inspektor/blob/main/src/postgres_driver/protocol_handler.rs#L688

**Comment by cphares** [comment]
I'm trying but I don't quite get it.  What logic would I add to the example in README.md to output `ast` as SQL?  I tried to crib from your example but I am failing to get it to work.

**Comment by poonai** [comment]
here is the minified example. 
```rust
use sqlparser::dialect::PostgreSqlDialect;
use sqlparser::parser::Parser;
fn main() {
    let dialect = PostgreSqlDialect {};
    let statements = Parser::parse_sql(&dialect, "SELECT * FROM USERS").unwrap();
    println!("AST TO RAW SQL QUERY");
    println!("{}", statements[0]);
}
```

check whether this helpful for you :)

**Comment by cphares** [comment]
Question answered!  Thx @poonai
