### ISSUE TITLE
Make `NOT EXISTS (subquery)` and `NOT IN (subquery)` more consistent in the AST

### ISSUE THREAD

**Issue by andygrove** [sqlparser-rs/sqlparser-rs#472]
The AST has one variant to support both `IN (subquery)` and `NOT IN (subquery)`:

``` rust
InSubquery {
    expr: Box<Expr>,
    subquery: Box<Query>,
    negated: bool,
},
```

However, the variant for EXISTS does not handle `NOT EXISTS`:

``` rust
Exists(Box<Query>)
```

`NOT EXISTS` is represented in the AST by wrapping `Exists` in a `UnaryOp` with `UnaryOperator::Not`.

It would be nice if we could use a more consistent approach.

**Comment by alamb** [comment]
I would prefer to see 

```rust
Exists {
      expr: Box<Expr>,
      subquery: Box<Query>,
}
```

**Comment by frolovdev** [comment]
I guess I can help 🚀

**Comment by frolovdev** [comment]
@alamb but what do you mean by `expr` in exists, because your comment isn't clear for me right now
