### ISSUE TITLE
Support escape string constant

### ISSUE THREAD

**Issue by houqp** [sqlparser-rs/sqlparser-rs#513]
The following query results in parser error `Expected ), found: '\n'`:

```sql
 SELECT d.datname as "Name",
       pg_catalog.pg_get_userbyid(d.datdba) as "Owner",
       pg_catalog.pg_encoding_to_char(d.encoding) as "Encoding",
       d.datcollate as "Collate",
       d.datctype as "Ctype",
       pg_catalog.array_to_string(d.datacl, E'\n') AS "Access privileges"
FROM pg_catalog.pg_database d
ORDER BY 1;
```

**Comment by houqp** [comment]
Do we want to unescape the string during parsing or delegate that to the consumer of the crate?

**Comment by ovr** [comment]
I already did that in https://github.com/sqlparser-rs/sqlparser-rs/commit/2c0886d9fe8cc0e6fb91ba63173d021384f24473

Thanks

**Comment by houqp** [comment]
Oh nice, thank you @ovr !
