### ISSUE TITLE
ToJson

### ISSUE THREAD

**Issue by asad-awadia** [sqlparser-rs/sqlparser-rs#531]
How can I setup conversion of statement to json?

Serde doesn't seem to be working - Do I need to pass `features`? to my cargo build?

The cli example works - but I want to do it as a dependency in my project

**Comment by asad-awadia** [comment]
`the trait `serde::ser::Serialize` is not implemented for `Statement``

**Comment by asad-awadia** [comment]
not sure why the cfg attribute is called serde when it clashes with the dependency serde
but the example cli uses json_example

**Comment by asad-awadia** [comment]
@nickolay @panarch

**Comment by panarch** [comment]
Serde is optional feature so you need to enable it.
```toml
sqlparser = { version = "0.18", features = ["serde"] }
```

ref. https://github.com/gluesql/gluesql/blob/dc994524c85ee304d52abd1297baf8305e6d56a4/core/Cargo.toml#L27

**Comment by asad-awadia** [comment]
@panarch do I have to include serde if I need to use it in my app? Like for my structs? or does it come in transitively?
