### ISSUE TITLE
UPDATE ... FROM ( subquery ) only supported in PostgreSQL

### ISSUE THREAD

**Issue by thomastyg** [sqlparser-rs/sqlparser-rs#534]
Hi 👋 

The `UPDATE <table> FROM (SELECT ...)` statement is only supported with `PostgreSQL` dialect.

It should be also supported for other technologies. 
Here are a few examples:
- [BigQuery](https://cloud.google.com/bigquery/docs/reference/standard-sql/dml-syntax#update_statement)
- [Snowflake](https://docs.snowflake.com/en/sql-reference/sql/update.html)
- [Redshift](https://docs.aws.amazon.com/redshift/latest/dg/c_Examples_of_UPDATE_statements.html)
- [SQL Server](https://docs.microsoft.com/fr-fr/sql/t-sql/queries/update-transact-sql?view=sql-server-ver16)

**Comment by alamb** [comment]
Thanks for the report. A contribution PR would be most welcome

**Comment by unvalley** [comment]
I'll take a look.
