### ISSUE TITLE
Add HiveQL dialect

### ISSUE THREAD

**Issue by andygrove** [sqlparser-rs/sqlparser-rs#56]
HiveQL is a defacto standard for data analytics and is well supported by BI tools such as Tableau. There are also ODBC and JDBC drivers available. I am interested in HiveQL support for DataFusion.

HiveQL Reference: https://cwiki.apache.org/confluence/display/Hive/LanguageManual

**Comment by l1x** [comment]
Hi @andygrove, I am working on such project and I have 10.000 queries to test with. I am reading the code but not sure how to add support to HiveQL yet. If you could just do a little bit of walk through with me I could possibly add HiveQL support. Let me know what you think.

**Comment by hntd187** [comment]
I've submitted an early state PR for this #235 I still have lots of work to do.

**Comment by AugustoFKL** [comment]
@alamb @andygrove isn't this "finished"? I mean, not completed, but the dialect itself is present already, right?

Can't this be closed?

**Comment by alamb** [comment]
👍

**Comment by alamb** [comment]
I agree this isn't tracking anything actionable at the moment -- we can file issues to track individual feature gaps as we find them

**Comment by hntd187** [comment]
I remember specifically bucketing and clustering in DDLs I did not add at the time as I had no good example of their usage to test against.
