### ISSUE TITLE
Is generated always as identity not supported.

### ISSUE THREAD

**Issue by sam-mmm** [sqlparser-rs/sqlparser-rs#560]
When trying  to parse 

```
CREATE TABLE table2
(
    column21 bigint primary key generated always as identity,
    column22 text
);
```

`let ast: Vec<ast::Statement> = SQLParser::parse_sql(&dialect, &contents).unwrap();`

dialect = PostgreSqlDialect
contents = above DDL

Will produce

> ParserError("Expected ',' or ')' after column definition, found: generated")

Above DDL is valid on PostgreSQL.
Am I doing something wrong or is `generated always as identity` not supported?

**Comment by AugustoFKL** [comment]
@sam-mmm that's a constraint not supported yet.

**Comment by sam-mmm** [comment]
Thanks,

https://github.com/sqlparser-rs/sqlparser-rs/pull/587
