### ISSUE TITLE
Support creating unsigned int types from SQL

### ISSUE THREAD

**Issue by Ted-Jiang** [sqlparser-rs/sqlparser-rs#575]
From https://github.com/apache/arrow-datafusion/pull/3146#discussion_r947656561

We should support creating unsigned int types from SQL.

For now seems all int are signed
```
❯ select 1;
+----------+
| Int64(1) |
+----------+
| 1        |
+----------+
1 row in set. Query took 0.004 seconds.
❯ select 10000;
+--------------+
| Int64(10000) |
+--------------+
| 10000        |
+--------------+
1 row in set. Query took 0.002 seconds.
❯ select -1;
+-----------+
| Int64(-1) |
+-----------+
| -1        |
+-----------+
1 row in set. Query took 0.001 seconds.

```

**Comment by AugustoFKL** [comment]
@alamb @Ted-Jiang isn't that fixed since https://github.com/sqlparser-rs/sqlparser-rs/pull/428?

I can't see what's the problem

**Comment by alamb** [comment]
I agree this ticket appears to have been fixed. Closing. Please let me know if I got that wrong @Ted-Jiang
