### ISSUE TITLE
Allow dialects to override prefix and infix parsing

### ISSUE THREAD

**Issue by andygrove** [sqlparser-rs/sqlparser-rs#580]
I would like the parser to be able to delegate to the dialect for prefix and infix parsing. This would make the crate much more flexible and extensible and allow us to remove many hacks in the core parser that were added to support parsing all the different dialects.

I am working on a prototype and hope to have a PR up soon. The change will be backwards compatible.

**Comment by xrl** [comment]
Is there any chance this would help with https://github.com/sqlparser-rs/sqlparser-rs/issues/577?
