### ISSUE TITLE
MySQL/MariaDB: Wrong LIMIT x,y to LIMIT x OFFSET y conversion

### ISSUE THREAD

**Issue by ZarTaen** [sqlparser-rs/sqlparser-rs#613]
While `LIMIT x, y` can be converted to a `LIMIT y OFFSET x` notation, it is currently converted to `LIMIT x OFFSET y`, which does not have the same meaning.

**Comment by AugustoFKL** [comment]
PR https://github.com/sqlparser-rs/sqlparser-rs/pull/642 for this fix :D
