### ISSUE TITLE
Does any plan to support tools for generating ast from online raw sql

### ISSUE THREAD

**Issue by baoyachi** [sqlparser-rs/sqlparser-rs#619]
like pest online parser: [pest editor](https://pest.rs/)

like this: 
![image](https://user-images.githubusercontent.com/10433001/191725702-bd87cd95-0641-4ef1-8940-7104b7e0f5de.png)

**Comment by AugustoFKL** [comment]
@baoyachi I'm 90% sure that there are no plans to do so. Maybe you can look into using this with an API and then having it on a web-service, but this is not the target of this crate and, therefore, not even in the near sight of being started.

**Comment by LeoDog896** [comment]
By any chance do you mean a playground? If so, I also do agree that a playground would be very nice.

**Comment by AugustoFKL** [comment]
@LeoDog896 sorry, forgot to answer.

I can't see any of the official maintainers working on that. @alamb is the most active one, and yet, he's here on a weekly, almost monthly base sometimes. Such a big feature would require a work-force that we don't have currently and possibly won't have for some time (or even never).

My recommendation would be for you to create a project individually using the sqlparser-rs as a dependency, and then work on it as you need. I'd love to help with reviews but can't say that would be able to help to code. I'm doing two colleges besides working, so adding open-source projects to my work routine isn't easy.

**Comment by LeoDog896** [comment]
Absolutely! I don't mind making it as a separate project - if it works properly well though, and if you don't mind, would you be open to adding it to the sqlparser-rs organization later on?

**Comment by AugustoFKL** [comment]
This is on @alamb hands.

He's the one in actual charge of the project. I just like to help here and there as possible.

**Comment by alamb** [comment]
> He's the one in actual charge of the project. I just like to help here and there as possible.

And I appreciate the help! I am sorry I am behind on sqlparser related things. I hope to spend some time reviewing / merging making a release shortly.

Realistically this crate is unlikely to undergo any major deign changes as described  https://github.com/sqlparser-rs/sqlparser-rs#contributing

>  and if you don't mind, would you be open to adding it to the sqlparser-rs organization later on?

The question in my mind is what do you hope to gain from adding it to the sqlparser-rs organization?

**Comment by LeoDog896** [comment]
Official maintenance - I don't mind maintaining it myself, though,

**Comment by alamb** [comment]
> Official maintenance - I don't mind maintaining it myself, though,

Makes sense -- I think given the lack of maintenance capacity of sqlparser-rs at the moment (I struggle to keep up) we probably don't have much in the way of capacity to provide
