### ISSUE TITLE
PostgreSQL Double precision correct support

### ISSUE THREAD

**Issue by AugustoFKL** [sqlparser-rs/sqlparser-rs#622]
PostgreSQL `DOUBLE PRECISION` is converted to `DOUBLE`, which is fine until we need to re-convert the query to string:

```rust
fn main() {

    let query = "CREATE TABLE tb (id DOUBLE PRECISION)";
    let dialect = PostgreSqlDialect{};
    let tokens = Tokenizer::new(&dialect, query).tokenize().unwrap();
    let mut parser = Parser::new(tokens, &dialect);

    println!("{}", parser.parse_statement().unwrap())
}
```

This prints:

```sql
CREATE TABLE tb (id DOUBLE)
```

Which isn't accepted by PostgreSQL.

Double precision is mentioned on our standard doc[1](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#approximate-numeric-type) and PostgreSQL docs [2](https://www.postgresql.org/docs/current/datatype-numeric.html)

[1]: https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#approximate-numeric-type
[2]: https://www.postgresql.org/docs/current/datatype-numeric.html

**Comment by augusto-vaultree** [comment]
@alamb can you close this, please?

It's already released, but I can't close it by myself
