### ISSUE TITLE
How to handle MySQL `CREATE SCHEMA` syntax

### ISSUE THREAD

**Issue by AugustoFKL** [sqlparser-rs/sqlparser-rs#644]
Currently, we only support `CREATE SCHEMA` and `CREATE DATABASE` with `IF NOT EXISTS`, which is quite small. However, to expand that, we need to keep one thing in mind: MySQL handles both the same ([1](https://dev.mysql.com/doc/refman/8.0/en/create-database.html)) and, therefore, handling them as one or another would lead to parsing problems.

However, we can't assume that they're the same, as they aren't at all. ([2](https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#schema-definition)).

My proposal is to handle the create schema following the standard, and `CREATE DATABASE` based on the dialects that have it (since it's not standard), such as Snowflake ([3](https://docs.snowflake.com/en/sql-reference/sql/create-database.html)), Postgresql ([4](https://www.postgresql.org/docs/current/sql-createdatabase.html)), and Oracle ([5](https://docs.oracle.com/database/121/SQLRF/statements_5005.htm#SQLRF01204)). For MySQL, I propose to handle `CREATE SCHEMA` as if it was a `CREATE DATABASE`, to avoid conflicts with the standard and duplicated implementations.

[1] : https://dev.mysql.com/doc/refman/8.0/en/create-database.html
[2] : https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html#schema-definition
[3] : https://docs.snowflake.com/en/sql-reference/sql/create-database.html
[4] : https://www.postgresql.org/docs/current/sql-createdatabase.html
[5] : https://docs.oracle.com/database/121/SQLRF/statements_5005.htm#SQLRF01204

**Comment by AugustoFKL** [comment]
@alamb any thoughts?

**Comment by alamb** [comment]
My basic thought / guideline is that that sqlparser crate should, as much as possible, parse SQL syntax but not apply semantic interpretation; Specifically, I think it should attempt to parse all SQL variants but avoid applying dialect specific semantic meaning 

So for example Ideally I would expect `CREATE SCHEMA` and `CREATE TABLE` to parse to different enum variants like `Statement::CreateSchema` and `Statement::CreateTable` and then downstream crates can decide if they want to treat them the same

In terms of different dialects supporting different subsets of syntax the general pattern is emerging is that `Dialect::Generic` should basically be a union of all possible syntaxes, as much as possible, and then restrict syntax in the other dialects. 

Does this make sense @AugustoFKL ? If so, I think I will try and document this goal in the README so other future contributors aren't confused (I don't think it is obvious)
