### ISSUE TITLE
Support Postgresql dollar-quoted string $$constant$$

### ISSUE THREAD

**Issue by duanzy47** [sqlparser-rs/sqlparser-rs#698]
Hello,

I noticed that the double dollar quoted string is not supported by the parser. Only the single $ identifier is supported, thus the parsing fails all the time for sql texts with dollar quoted strings.
As it is a very convenient way to write complicated strings, dollar-quoting is largely used in the Postgres community. Could you please support it in the Postgres dialect? 

Thanks in advance ;)

**Comment by omer-shtivi** [comment]
Suggestion:
Add another QuotedString type: `DoubleDollarQuotedString` but I think it should go in after we finish the switch to Enum for QuoteStyle, that way we are not bounded to chars as quoting style
