### ISSUE TITLE
Use pedantic rust linter and super linter

### ISSUE THREAD

**Issue by AugustoFKL** [sqlparser-rs/sqlparser-rs#700]
I think using the pedantic linter [(1)](https://github.com/rust-lang/rust-clippy) and super linter [(2)](https://github.com/github/super-linter) is really reasonable, and could improve the code quality a lot.

What do you think @alamb 

[1] : https://github.com/rust-lang/rust-clippy
[2] : https://github.com/github/super-linter

**Comment by alamb** [comment]
I think these are already run in our CI system, for example

https://github.com/sqlparser-rs/sqlparser-rs/actions/runs/3385991687/jobs/5624817335
https://github.com/sqlparser-rs/sqlparser-rs/actions/runs/3385991687/jobs/5624817057

Maybe I misunderstand what you are suggesting

**Comment by AugustoFKL** [comment]
Currently we just use the standard Clippy.

Super linter is a non-rust related.

And pedantic considers more idiomatic linters, check the doc [(1)](https://rust-lang.github.io/rust-clippy/master/) about pedantic linters.

[1] : https://rust-lang.github.io/rust-clippy/master/

**Comment by alamb** [comment]
In general I think we should strive to make contributing to (and maintaining this crate) as easy as possible. Part of doing that is using well known rust tools so contributors don't have to install additional dependencies I think

I have not run into the different linter referred to above -- it might be interesting to try it out with a PR to see what difference it makes practically
