### ISSUE TITLE
Does sqlparser-rs support Left Semi/Left Anti/Right Semi/Right Anti Join ?

### ISSUE THREAD

**Issue by mingmwang** [sqlparser-rs/sqlparser-rs#712]
From the code based, looks like they are unsupported as of now.

https://github.com/sqlparser-rs/sqlparser-rs/blob/f7817bc7c257b6db76bb19b83033a7f2f001313b/src/ast/query.rs#L570-L581

**Comment by mingmwang** [comment]
@alamb

**Comment by Dandandan** [comment]
There is no specific syntax right now in sqlparser-rs indeed (most SQL dialects don't support it).

**Comment by mingmwang** [comment]
Can we add those?

**Comment by alamb** [comment]
I think SQL queries typically don't have ANTI/SEMI joins directly  -- instead they have correlated `EXISTS` and `IN` subqueries

Such correlated subqueries are typically implemented using various combinations of ANTI/SEMI joins as a performance optimization (rather than re-running each subquery )

What is the usecase of adding `SEMI JOIN` to the SQL grammar?

**Comment by mingmwang** [comment]
Some of the engines support ANTI/SEMI joins directly.  And yesterday I found there was issue within DataFusions's RIGHT ANTI/RIGHT SEMI Join implementation and try to write some UTs to verify it, but found I can not just because  those SQL syntaxes are not directly supported, and they are converted from other forms, which makes the UT writings not very straightforward.

**Comment by alamb** [comment]
I think if there is some precident (like a reference to a sql dialect in sqlparser that supports syntax like SEMI JOIN, etc) we would definitely accept the PR

**Comment by mingmwang** [comment]
Apache Calcite:

https://github.com/apache/calcite/blob/main/site/_docs/algebra.md

SparkSQL

https://github.com/apache/spark/blob/5c43da6858721664318c3cdbcb051231b0e98175/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBaseParser.g4#L708-L716
