### ISSUE TITLE
Support `EXCLUDE` and `RENAME` in Snowflake

### ISSUE THREAD

**Issue by CorentinLimier** [sqlparser-rs/sqlparser-rs#716]
Hello,

Snowflake added two SQL keywords : `EXCLUDE` and `RENAME`

ex of query : 

```sql
SELECT 
    *
    EXCLUDE (col_a)
    RENAME col_b as b
FROM data
```

Link to documentation : https://docs.snowflake.com/en/sql-reference/sql/select.html

Thank you

**Comment by AugustoFKL** [comment]
@CorentinLimier https://github.com/sqlparser-rs/sqlparser-rs/pull/721 exclude PR
