### ISSUE TITLE
Add `COMPRESSION` as a `Keyword`

### ISSUE THREAD

**Issue by HaoYang670** [sqlparser-rs/sqlparser-rs#718]
The Datafusion recently supports a new SQL syntax `COMPRESSION TYPE`: https://github.com/apache/arrow-datafusion/issues/3641

However, the word `COMPRESSION` is not a `Keyword` recently. I want to add it as a `Keyword` so that we can parse this syntax in Datafusion easily: https://github.com/apache/arrow-datafusion/issues/4262

**Comment by AugustoFKL** [comment]
@HaoYang670 created a PR for this: https://github.com/sqlparser-rs/sqlparser-rs/pull/720
