### ISSUE TITLE
Parse identifiers function

### ISSUE THREAD

**Issue by Jefffrey** [sqlparser-rs/sqlparser-rs#805]
Extract function from datafusion to here

https://github.com/apache/arrow-datafusion/blob/d5077b55ef39e5376ace93d4e9068b94b678e7f1/datafusion/common/src/table_reference.rs#L228-L279

Allowing use of this function to parse a string containing identifiers (not a SQL string)

**Comment by AugustoFKL** [comment]
@Jefffrey, can you please give an example (s) of what queries you're running, what you're trying to do, the problem, and what you expect to achieve?

Sorry, but going through data fusion code isn't on my immediate plans. But it seems simple, so once I understand it, I could do it (or you could do it as well if you feel like it).

**Comment by Jefffrey** [comment]
Yeah this is simple upstreaming of function from DataFusion to here, where it's more appropriate. It's mainly for parsing identifiers, especially for taking into consideration quoting, e.g. parse `catalog."data.""base"."TABLE"` into a list of `Idents`

Can see the unit tests for some example usages:

https://github.com/apache/arrow-datafusion/blob/d5077b55ef39e5376ace93d4e9068b94b678e7f1/datafusion/common/src/table_reference.rs#L305-L322

I've been meaning do to it since I did write that original function in DataFusion, but just haven't gotten around to it yet.

@AugustoFKL
