### ISSUE TITLE
In correct serialization of `DISTINCT ON()` syntax with postgres

### ISSUE THREAD

**Issue by nicksrandall** [sqlparser-rs/sqlparser-rs#806]
Here is the failing sql: 

```sql
SELECT
   DISTINCT ON (column1) column_alias,
   column2
FROM
   table_name
ORDER BY
   column1,
   column2;
```

Note that this parses without errors because it parses the `ON (column1)` as a function.

When serializing back to string from ast, it produces: 

```sql
SELECT DISTINCT ON(column1) AS column_alias, column2 FROM table_name ORDER BY column1, column2
```

The `AS` should not be there (it is an error in Postgres)

**Comment by AugustoFKL** [comment]
@nicksrandall, thanks for the report! Are you planning to work on this, or can I do that?

**Comment by nicksrandall** [comment]
@AugustoFKL go for it. I don't have bandwidth ATM.
