### ISSUE TITLE
Propose adding AugustoFKL as maintainer of sqlparser-rs

### ISSUE THREAD

**Issue by alamb** [sqlparser-rs/sqlparser-rs#808]
This project need more maintainer capacity to do its users justice and help drive things forward. 

I do enough to keep it from going entirely dormant, but that is really not sufficient for a healthy project; Having contributors wait weeks for review feedback is a bad experience for everyone involved and for that I apologize.

@AugustoFKL  has shown good judgement and has helped drive the project along with many reviews the last few months. I trust he will use his judgement to ensure the project remains easy to contribute to, easy to use, solicit user feedback, and not cause required massive API churn for existing users.

If you have any comments, please share them here.

I look forward to a bright future for sqlparser-rs

**Comment by AugustoFKL** [comment]
@alamb thanks a lot!

As we already agreed, massive API changes are something other than what we can support right now, as the project is quite stable.

I'd love to contribute, mainly on approving small PRs, and keep raising discussion on big PRs (as the API visitor that we are developing right now);

It means a lot for me, and I compromise in being more active!

**Comment by Dandandan** [comment]
I fully support adding @AugustoFKL as maintainer of the project.

**Comment by alamb** [comment]
cc @maxcountryman @nickolay  as well

**Comment by alamb** [comment]
I have invited @AugustoFKL to be a committer on this repository and look forward to some additional momentum in this repository.

**Comment by alamb** [comment]
Due to unforeseen circumstances, @AugustoFKL  has told me he may not be able to contribute any more to sqlparser in the near future.

**Comment by alamb** [comment]
I started a discussion about moving sqlparser into Apache Software Foundation governance: https://github.com/sqlparser-rs/sqlparser-rs/issues/1294. Please let us know what you think
