### ISSUE TITLE
Add support for trailing commas

### ISSUE THREAD

**Issue by ankrgyl** [sqlparser-rs/sqlparser-rs#809]
Outside of BigQuery, and in contexts outside of the project list, it's useful to allow trailing commas (e.g. DuckDB supports them, and users building their own query tools might want to).

Personally, I think it'd be useful to just always allow them, but I can understand that (a) this could break compatibility and (b) could break use cases where people want to validate that queries parse against a particular database (e.g. postgres) with this library.

I'd propose we add some flags that allow you to control features of the parser, more granularly than vendor'd name dialects. Eventually, we could even decompose dialects into these options, but to start, it could be a separate feature.

**Comment by ankrgyl** [comment]
PR: https://github.com/sqlparser-rs/sqlparser-rs/pull/810

**Comment by alamb** [comment]
I agree this would be great to support (I often find myself being annoyed at the comma strictness of classic SQL)

**Comment by alamb** [comment]
Done in https://github.com/sqlparser-rs/sqlparser-rs/pull/810
