### ISSUE TITLE
Inconsistent handling of Postgres infix operators

### ISSUE THREAD

**Issue by joocer** [sqlparser-rs/sqlparser-rs#816]
There appear to be some Postgres operators which are supported in the base dialect and some that are only supported in the Postgres dialect, but I'm not able to work out why from looking at the code. See below, it looks like `>>` is in Postgres and Generic, but `~` is everywhere.

~~~rust
            Token::ShiftRight if dialect_of!(self is PostgreSqlDialect | GenericDialect) => {
                Some(BinaryOperator::PGBitwiseShiftRight)
            }
            Token::Sharp if dialect_of!(self is PostgreSqlDialect) => {
                Some(BinaryOperator::PGBitwiseXor)
            }
            Token::Tilde => Some(BinaryOperator::PGRegexMatch),
            Token::TildeAsterisk => Some(BinaryOperator::PGRegexIMatch),
~~~

Is this a bug in the implementation (should tilde be only applicable to Postgres / ShiftRight be available to all) or is there a missing comment as to why this distinction exists?

**Comment by AugustoFKL** [comment]
@joocer, the operator handling is quite faulty right now for two reasons:
- The operators vary from dialect;
- (more critical) Their precedence varies between dialects.

The fact that we try to do all parsing together makes it hard to handle specific logic properly. As I commented on #814, I would love to review a new implementation, but I can work directly on that. It is too much, and for now, I only plan on working on the following:
- Review PRs
- Review issues
- Solve *small* generic PRs (e.g., add a keyword for a statement here, a data type there, etc.)
- MySQL and PostgreSQL specific syntax

Besides that, I can't guarantee anything for the next month, at least considering the pacing I'm taking. Sorry about that.

**Comment by joocer** [comment]
Thanks @AugustoFKL, rather than two issues that touch on each other, I suggest this one be closed off, it looks like michael-2956 is probably in a better position to progress as I'm not much of a rust developer (I'm using this library in Python via SqlOxide).

**Comment by AugustoFKL** [comment]
@joocer lovely to know! Thanks for the information; it makes me wanna work even more here to support everyone using this!!

Promise you that the precedence will be fixed within the next month, even if @michael-2956 doesn't work on this.
