### ISSUE TITLE
Mysql multi-table deletes is not supported

### ISSUE THREAD

**Issue by AviRaboah** [sqlparser-rs/sqlparser-rs#854]
The following query is not supported - 

DELETE t1, t2 FROM t1 INNER JOIN t2 INNER JOIN t3
WHERE t1.id=t2.id AND t2.id=t3.id;

got - ParserError("Expected FROM, found: t1")

is this query are going to be supported near future ?

thanks.

**Comment by ankrgyl** [comment]
Hi @AviRaboah as far as I know, there are no active plans to implement this feature. However, we welcome contributions and would gladly collaborate with you if you'd like to take a stab at implementing it.

**Comment by ankrgyl** [comment]
Hi @AviRaboah, yes that's intended — the workflow to use is a [pull request](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests) which allows the maintainers of this repo to review your code before it's merged in.

You usually do this by forking the repo, pushing a branch, and then submitting a pull request. Let us know if you have any questions.

**Comment by AviRaboah** [comment]
That’s exactly what I did bot for some reason got status code 403
