### ISSUE TITLE
Support `UNION (ALL) BY NAME` syntax (duckdb, spark)

### ISSUE THREAD

**Issue by alexander-beedie** [sqlparser-rs/sqlparser-rs#899]
This is a very useful form of `UNION` that has the backend align the columns on either side of the union: https://duckdb.org/docs/sql/query_syntax/setops.html#union-all-by-name.

Would be wonderful to have parsing support :)
Many thanks!

---
```sql
SELECT * FROM table_x UNION BY NAME SELECT * FROM table_y;
```

**Comment by alamb** [comment]
Kudos to @parkma99  for the PR https://github.com/sqlparser-rs/sqlparser-rs/pull/915
