### ISSUE TITLE
Support field names in BigQuery STRUCT

### ISSUE THREAD

**Issue by gomesfernandes** [sqlparser-rs/sqlparser-rs#901]
I want to parse BigQuery queries that **assign field names** in their STRUCTs.  
Example:
```SQL
SELECT
    STRUCT(
        CONCAT(user.first_name, ' ', user.last_name) AS full_name,
        user.email AS email,
    ) AS viewer
FROM users
```

This corresponds to the typeless struct syntax mentioned in the [BigQuery documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types#typeless_struct_syntax), and which is as follows:  
 `STRUCT( expr1 [AS field_name] [, ... ])`

Note that without the aliases, the query is parsed successfully:
```SQL
SELECT
    STRUCT(
        CONCAT(user.first_name, ' ', user.last_name),
        user.email
    ) AS viewer
FROM users
```

It seems there is already [an ongoing PR](https://github.com/sqlparser-rs/sqlparser-rs/pull/817) related to BigQuery STRUCTs, but the description does not mention support for field names/aliases.

**Comment by alamb** [comment]
Perhaps @togami2864  has some time to revive https://github.com/sqlparser-rs/sqlparser-rs/pull/817, and if not perhaps someone else can pick it up
