### ISSUE TITLE
SUBSTRING function for MsSqlDialect queries is regenerated incorrectly

### ISSUE THREAD

**Issue by jmaness** [sqlparser-rs/sqlparser-rs#914]
For Microsoft SQL Server, the syntax of the `SUBSTRING` function (described at https://learn.microsoft.com/en-us/sql/t-sql/functions/substring-transact-sql?view=sql-server-ver16) is `SUBSTRING(expr, start, len)`. With sqlparser-rs, this parses correctly:

```
SELECT SUBSTRING('foobar', 1, 2)
```

but then is regenerated from the AST as

```
SELECT SUBSTRING('foobar' FROM 1 FOR 2);
```

which is not valid for Microsoft SQL Server with the error message `[S0001][156] Line 1: Incorrect syntax near the keyword 'FROM'.`

For other database dialects, variants such as `SUBSTRING(expr [FROM start] [FOR len])` are supported, but Microsoft SQL Server does not appear to support these variants.

From looking at the `Display` impl for `Expr`, the dialect does not appear to be available, so would an acceptable alternative be to modify the `Expr::Substring` type and parser to store information describing the specific `SUBSTRING` variant?

**Comment by alamb** [comment]
> From looking at the Display impl for Expr, the dialect does not appear to be available, so would an acceptable alternative be to modify the Expr::Substring type and parser to store information describing the specific SUBSTRING variant?

Hi @jmaness  -- thanks for filing the ticket. 

Yes, I think that is consistent with how similar situations are handled elsewhere in this crate. For example `CURRENT_TIMESTAMP` vs `CURRENT_TIMESTAMP()` in 

https://github.com/sqlparser-rs/sqlparser-rs/blob/eb288487a6a938b45004deda850e550a74fcf935/src/ast/mod.rs#L3494-L3496

**Comment by jmaness** [comment]
Thanks @alamb, I'll follow a similar pattern and file a PR.
