### ISSUE TITLE
sqlparser breaks CURRENT_TIMESTAMP for sqlite

### ISSUE THREAD

**Issue by lovasoa** [sqlparser-rs/sqlparser-rs#918]
In [SQLPage](https://github.com/lovasoa/SQLpage), we parse SQL queries using sqlparser in order to be able to modify them, and then dump them as text to run them on the database. This requires the process of parsing and then stringifying back not to break the semantics nor the syntax of the query.

However, the following SQLite query:

```sql
SELECT CURRENT_TIMESTAMP;
```

when parsed and then dumped back, gives:

```sql
SELECT CURRENT_TIMESTAMP();
```

This breaks the syntax for SQLite, which gives

```
sqlite> SELECT CURRENT_TIMESTAMP();
Error: in prepare, near "(": syntax error (1)
```

**Comment by alamb** [comment]
Thanks @lovasoa  the "do we have trailing parens" is already tracked by the "special" flag:

**Comment by lovasoa** [comment]
@alamb : thanks for the pointers ! I opened a PR
