### ISSUE TITLE
An exception occurred while parsing the MySQL CREATE TABLE statement. ParserError("Expected end of statement, found: AUTO_INCREMENT")

### ISSUE THREAD

**Issue by artorias1024** [sqlparser-rs/sqlparser-rs#920]
<img width="1231" alt="image" src="https://github.com/sqlparser-rs/sqlparser-rs/assets/82564604/b0d9afbc-5958-4d1e-91b3-acf5b88921dd">

<img width="1512" alt="image" src="https://github.com/sqlparser-rs/sqlparser-rs/assets/82564604/73e2f6bc-abbd-4888-b21b-c284f07e7e92">

**Comment by artorias1024** [comment]
ParserError("Expected end of statement, found: AUTO_INCREMENT")

**Comment by alamb** [comment]
Thank you -- it would be great to add support for the AUTO increment syntax in sqlparser
