### ISSUE TITLE
No support for `ANY` and `ALL` use in `WHERE`

### ISSUE THREAD

**Issue by SeanTroyUWO** [sqlparser-rs/sqlparser-rs#936]
Seems like the parser only supports the use of `ANY` and `ALL` in `SELECT`, not `WHERE`.
This form seems to work:
```
SELECT ALL column_name(s)
FROM table_name
WHERE condition;
```
There's a test for it in `tests/sqlparser_common.rs line: 1539`
This does not supported:
```
SELECT column_name(s)
FROM table_name
WHERE column_name operator ALL
  (SELECT column_name
  FROM table_name
  WHERE condition); 
```
I'm not sure why this is the case. Please let me know if this is intentional. If not I can create a PR.

**Comment by SeanTroyUWO** [comment]
The defining factor might actually be the use of a subquery after `ALL` of `ANY`.

**Comment by SeanTroyUWO** [comment]
I think I have a good handle on the issue, can I submit a PR that adds or changes elements to `enum Expr`?  This may be a breaking change.

**Comment by alamb** [comment]
Hi @SeanTroyUWO  -- a PR would be most helpful

I am not totally sure what `ALL` and `ANY` mean in SQL, but here is one for adding something similar with `UNION ALL`: https://github.com/sqlparser-rs/sqlparser-rs/pull/915

**Comment by SeanTroyUWO** [comment]
> Hi @SeanTroyUWO -- a PR would be most helpful
> 
> I am not totally sure what `ALL` and `ANY` mean in SQL, but here is one for adding something similar with `UNION ALL`: #915

Okay finally getting around to this. The issue is I might break code that depends on the current implementation of `ALL` and `ANY`. Is that okay?
