### ISSUE TITLE
how parse 100G sql file to csv files?

### ISSUE THREAD

**Issue by hktalent** [sqlparser-rs/sqlparser-rs#945]
how parse 100G sql file to csv files?
thanks

**Comment by AugustoFKL** [comment]
@hktalent, what exactly do you want to parse? The question is too broad. What do you want to accomplish by that?

Note that the parser, as stated multiple times, is permissive. If you want to parse for syntax validation, then this isn't the place to. 

In the end, the parser doesn't exporting CSV as long as I'm aware. Check the [README.md](https://github.com/sqlparser-rs/sqlparser-rs/blob/main/README.md), there is an explanation of everything that you can or cannot do.

@alamb, this could be closed IMHO.

**Comment by alamb** [comment]
sqlparser isn't a streaming parser (aka it will parse the entire tree into memory).

If you have 100GB of SQL with data, like `INSERT INTO .... VALUES ...` one thing you could do would be to "tokenize" the sql outside of sqlparser (aka split on `\n`) and then parse each line / statement individually

**Comment by hktalent** [comment]
@alamb @AugustoFKL 
Thanks, I have written a simple parser myself, and the test passes
