### ISSUE TITLE
Error: SchemaParse(ParserError("Expected a list of columns in parentheses, found: KEY"))

### ISSUE THREAD

**Issue by artorias1024** [sqlparser-rs/sqlparser-rs#961]
The SQL statement I want to parse is: 
```sql
CREATE TABLE `funds_sale` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT COMMENT '',
  PRIMARY KEY (`id`, `cid`),
  UNIQUE KEY `uk_bill_str` (`cid`, `bill_str`),
  KEY `idx_biz_str` (`cid`, `biz_str`)
  ) ENGINE = InnoDB AUTO_INCREMENT = 878936 DEFAULT CHARSET = utf8mb4 COMMENT = ''

```
 but I encountered an error.
```rust
Error: SchemaParse(ParserError("Expected a list of columns in parentheses, found: KEY"))
```

**Comment by artorias1024** [comment]
<img width="1090" alt="image" src="https://github.com/sqlparser-rs/sqlparser-rs/assets/82564604/004df0e9-f7e5-40ce-910a-58afb7878710">

<img width="922" alt="image" src="https://github.com/sqlparser-rs/sqlparser-rs/assets/82564604/3a1eb52f-e961-4587-a711-8b54edb3568d">



Should we add a branch judgment, if the next token is the keyword Key, then continue to iterate downward?

**Comment by alamb** [comment]
> Should we add a branch judgment, if the next token is the keyword Key, then continue to iterate downward?

That seems reasonable to me
